config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "site#home"
  get '/train/:model/:class/:id', to: "site#show", as: :train

  # sessions => CALL THIS CUSTOM?
  # resources :sessions, only: [:destroy]
  # delete '/clear', to: "sessions#destroy"

  #css user download
  # get '/user/download', to: "users#download",  as: :download

  #users
  post '/user', to: "users#create", as: :user_create
  get '/user/:cookie_id', to: "users#index", as: :user
  get '/user/:model/:class/:id', to: "users#show", as: :user_train  


  #stats pages
  get '/stats', to: "site#index"
  get '/h1/stats', to: "h1s#show"
  get '/h2/stats', to: "h2s#show"
  get '/h3/stats', to: "h3s#show"
  get '/h4/stats', to: "h4s#show"
  get '/h5/stats', to: "h5s#show"
  get '/button/stats', to: "buttons#show"
  get '/image/stats', to: "images#show"
  get '/listelement/stats', to: "listelements#show"
  get '/paragraph/stats', to: "paragraphs#show"
  get '/section/stats', to: "sections#show"
  get '/body/stats', to: "bodies#show"

  #Extracting CSS to DB
  post '/h1/:id', to: "h1s#create", as: :train_h1
  post '/h2/:id', to: "h2s#create", as: :train_h2
  post '/h3/:id', to: "h3s#create", as: :train_h3
  post '/h4/:id', to: "h4s#create", as: :train_h4
  post '/h5/:id', to: "h5s#create", as: :train_h5
  post '/button/:id', to: "buttons#create", as: :train_button
  post '/paragraph/:id', to: "paragraphs#create", as: :train_paragraph
  post '/image/:id', to: "images#create", as: :train_image
  post '/section/:id', to: "sections#create", as: :train_section
  post '/body/:id', to: "bodies#create", as: :train_body
  post '/li/:id', to: "listelements#create", as: :train_li
end

app/models/body.rb
class Body < ApplicationRecord
  has_many :body_properties
  belongs_to :user, required: false
end

app/models/button.rb
class Button < ApplicationRecord
  has_many :button_properties
  belongs_to :user, required: false
end

app/models/h1.rb
class H1 < ApplicationRecord
  has_many :h1_properties
  belongs_to :user, required: false
end

app/models/h1_property.rb
class H1Property < ApplicationRecord
  belongs_to :h1
end

app/models/h2.rb
class H2 < ApplicationRecord
  has_many :h2_properties
  belongs_to :user, required: false
end

app/models/h2_property.rb
class H2Property < ApplicationRecord
  belongs_to :h2
end

app/models/h3.rb
class H3 < ApplicationRecord
  has_many :h3_properties
  belongs_to :user, required: false
end

app/models/h3_property.rb
class H3Property < ApplicationRecord
  belongs_to :h3
end

app/models/h4.rb
class H4 < ApplicationRecord
  has_many :h4_properties
  belongs_to :user, required: false
end

app/models/h4_property.rb
class H4Property < ApplicationRecord
  belongs_to :h4
end

app/models/h5.rb
class H5 < ApplicationRecord
  has_many :h5_properties
  belongs_to :user, required: false
end

app/models/image.rb
class Image < ApplicationRecord
  has_many :image_properties
  belongs_to :user, required: false
end

app/models/paragraph.rb
class Paragraph < ApplicationRecord
  has_many :paragraph_properties
  belongs_to :user, required: false
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :section_properties
  belongs_to :user, required: false
end

app/models/user.rb
class User < ApplicationRecord
  # cookie_id uniqueness: :true
  has_many :h1s
  has_many :h2s
  has_many :h3s
  has_many :h4s
  has_many :h5s
  has_many :bodies
  has_many :buttons
  has_many :images
  has_many :listelements
  has_many :paragraphs
  has_many :sections


  def initialize_user
    h1 = self.h1s.create!
    h1.h1_properties.create!(fontsize: 36, letterspacing: 4, texttransformation: "capitalize", fontweight: 700)

    h2 = self.h2s.create!
    h2.h2_properties.create!(fontsize: 32, letterspacing: 2, texttransformation: "lowercase", fontweight: 400, wordspacing: 5)

    h3 = self.h3s.create!
    h3.h3_properties.create!(fontsize: 28, letterspacing: 3, texttransformation: "uppercase", fontweight: 300, wordspacing: 3)

    h4 = self.h4s.create!
    h4.h4_properties.create!(fontsize: 22, letterspacing: 1, texttransformation: "uppercase", fontweight: 300, wordspacing: 3)

    h5 = self.h5s.create!
    h5.h5_properties.create!(fontsize: 14, letterspacing: 2, texttransformation: "capitalize", fontweight: 200, wordspacing: 2)

    button_1 = self.buttons.create!
    button_1.button_properties.create!(
      fontsize: 16, texttransformation: "capitalize", fontweight: 200, letterspacing: 3, padding: 15,
        border: 5, borderradius: 10, border_style: "solid", border_hue: 50, border_saturation: 50, border_luminosity: 50,
        bg_hue: 0, bg_saturation: 100, bg_luminosity: 100,
        color_hue: 0, color_saturation: 0, color_luminosity: 0
      )

    button_2 = self.buttons.create!
    button_2.button_properties.create!(
      fontsize: 16, texttransformation: "capitalize", fontweight: 200, letterspacing: 3, padding: 15,
        border: 5, borderradius: 10, border_style: "solid", border_hue: 51, border_saturation: 51, border_luminosity: 51,
        bg_hue: 1, bg_saturation: 99, bg_luminosity: 99,
        color_hue: 1, color_saturation: 1, color_luminosity: 1
      )

    # button_3 = self.buttons.create!
    # button_3.button_properties.create!(
    #   fontsize: 16, texttransformation: "capitalize", fontweight: 200, letterspacing: 3, padding: 15,
    #     border: 5, borderradius: 10, border_style: "solid", border_hue: 52, border_saturation: 52, border_luminosity: 52,
    #     bg_hue: 2, bg_saturation: 98, bg_luminosity: 98,
    #     color_hue: 2, color_saturation: 2, color_luminosity: 2
    #   )


    li = self.listelements.create!
    li.listelement_properties.create!(fontsize: 14, letterspacing: 6, texttransformation: "capitalize", fontstyle: "italic")

    paragraph = self.paragraphs.create!
    paragraph.paragraph_properties.create!(textalign: "left", fontsize: 12, wordspacing: 3, padding: 5, indent: 25)

    paragraph2 = self.paragraphs.create!
    paragraph2.paragraph_properties.create!(textalign: "center", fontsize: 14, wordspacing: 4, padding: 10, indent: 15)

    image = self.images.create!
    image.image_properties.create!(height: 250, width: 250, border: 1, borderradius: 5, padding: 15, 
      border_hue: 180, border_luminosity: 50, border_saturation: 50
      )

    section_1 = self.sections.create!
    section_1.section_properties.create!(
      color_hue: 0, color_luminosity: 0, color_saturation: 0,
      bg_hue: 0, bg_luminosity: 100, bg_saturation: 100,
      )
    section_2 = self.sections.create!
    section_2.section_properties.create!(
      color_hue: 1, color_luminosity: 1, color_saturation: 1,
      bg_hue: 1, bg_luminosity: 99, bg_saturation: 99,
      )
    section_3 = self.sections.create!
    section_3.section_properties.create!(
      color_hue: 2, color_luminosity: 2, color_saturation: 2,
      bg_hue: 2, bg_luminosity: 98, bg_saturation: 98,
      )
    section_4 = self.sections.create!
    section_4.section_properties.create!(
      color_hue: 3, color_luminosity: 3, color_saturation: 3,
      bg_hue: 3, bg_luminosity: 97, bg_saturation: 97,
      )

    body = self.bodies.create!
    heading = self.bodies.create!
    bodyfont = body.body_properties.create!(fontfamily: "Georgia")
    headingfont = heading.body_properties.create!(fontfamily: "Arial")
  end
end

app/helpers/h1s_helper.rb
module H1sHelper
end

app/helpers/h2s_helper.rb
module H2sHelper
end

app/helpers/h3s_helper.rb
module H3sHelper
end

app/helpers/h4s_helper.rb
module H4sHelper
end

app/helpers/h5s_helper.rb
module H5sHelper
end

app/views/partials/_about_info.html.erb
Youi is many things. Initially, it is a website where its styles are crowd-sourced. This means that any person in the entire world can contribute to how the website looks (even your grandma). Additionally, Youi offers individual users to build custom CSS templates using our engine. This tool can help the non-technical sort create beautiful websites, non-artistic developers enhance their websites, or anyone who is looking to have some creative fun on the Internet! Youi takes away the frustration of stylizing sties with limiting tools such as WordPress or Squarespace, and really puts you in the driver’s seat.

app/views/partials/_faces_info.html.erb
Psychologists at the University of Glasgow carried out an interesting experiment. Combining “composite portraiture” and modern technology, the project averages thousands of women's faces, voted on by people of the Internet. According to the study, generally “attractive”-looking faces were procured out of the experiment through 41 different countries and ethnicities. Youi believes that this methodology can be used to discover what you think are the most ideal website styles.

app/views/partials/_instructions.html.erb
<div class='main-instructions'>
  <span class='loud'>
      <%= @pronoun %>'ve changed <%= @y %>our style <%= count %> times
  </span>
  <div class='row'>
    <div class='col-md-7 sub-instructions'>
      <h2>Instructions:</h2>
      <ul>
        <li><strong>Things you can change: </strong>(Try hovering over stuff)</li>
        <li>
          <div class='green'>
            Individual Elements
          </div>
        </li>
        <li>
          <div class='blue'>
            Entire Sections
          </div>
        </li>
        <li>
          <div class='info-panel'>
            <h3 data-toggle="modal" data-target="#instructions"><strong>How It Works</strong></h3>
            <%= link_to user_path(@cookie) do %>
              <h3><strong>Custom Template</strong></h3>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
    <div class='col-md-5'>
      <div class='special-buttons'>
        <ul>
          <div class='instruction-buttons section active-section'>
            
            <li>
              <button class="not edit can-explore button-selector-2 button-selector-<%= @button_selector_id_2 %>"
                  data-toggle="tooltip" data-placement="right" 
                  data-html="true"
                  title="
                  <div class='big-tips tooltip-special'>
                    <h3>Hover Button</h3>
                    <ul>
                      <li>
                    Font Size: <%= @button_2_font_size %>px
                      </li>
                      <li>
                    Font Weight: <%= @button_2_font_weight %>
                      </li>
                      <li>
                    Text Transformation: <%= @button_2_text_transform %>
                      </li>
                      <li>
                    Letter Spacing: <%= @button_2_letter_spacing %>px
                      </li>
                      <li>
                    Padding: <%= @button_2_padding %>px
                      </li>
                      <li>
                    Border Size: <%= @button_2_border %>px
                      </li>
                      <li>
                    Border-Radius: <%= @button_2_border_radius %>px
                      </li>
                      <li>
                    Border-Style: <%= @button_2_border_style %>
                      </li>
                      <li>
                    Color (hsl): (
                      <%= @button_2_color_hue %>, 
                      <%= @button_2_color_saturation %>%, 
                      <%= @button_2_color_luminosity %>%)
                      </li>
                      <li>
                    Border-color (hsl): (
                      <%= @button_2_border_color_hue %>, 
                      <%= @button_2_border_color_saturation %>%, 
                      <%= @button_2_border_color_luminosity %>%)
                      </li>
                      <li>
                    Background-Color (hsl): (
                      <%= @button_2_bg_color_hue %>, 
                      <%= @button_2_bg_color_saturation %>%, 
                      <%= @button_2_bg_color_luminosity %>%)
                      </li>
                    </ul>
                  </div>"
                  >
                Hovers
              </button>
              <span class="edit-mode not">On</span>
            </li>
            <li>
              <button class="not explore can-explore button-selector-2 button-selector-<%= @button_selector_id_2 %>"
                  data-toggle="tooltip" data-placement="right" 
                  data-html="true"
                  title="
                  <div class='big-tips tooltip-special'>
                    <h3>Tooltip Button</h3>
                    <ul>
                      <li>
                    Font Size: <%= @button_2_font_size %>px
                      </li>
                      <li>
                    Font Weight: <%= @button_2_font_weight %>
                      </li>
                      <li>
                    Text Transformation: <%= @button_2_text_transform %>
                      </li>
                      <li>
                    Letter Spacing: <%= @button_2_letter_spacing %>px
                      </li>
                      <li>
                    Padding: <%= @button_2_padding %>px
                      </li>
                      <li>
                    Border Size: <%= @button_2_border %>px
                      </li>
                      <li>
                    Border-Radius: <%= @button_2_border_radius %>px
                      </li>
                      <li>
                    Border-Style: <%= @button_2_border_style %>
                      </li>
                      <li>
                    Color (hsl): (
                      <%= @button_2_color_hue %>, 
                      <%= @button_2_color_saturation %>%, 
                      <%= @button_2_color_luminosity %>%)
                      </li>
                      <li>
                    Border-color (hsl): (
                      <%= @button_2_border_color_hue %>, 
                      <%= @button_2_border_color_saturation %>%, 
                      <%= @button_2_border_color_luminosity %>%)
                      </li>
                      <li>
                    Background-Color (hsl): (
                      <%= @button_2_bg_color_hue %>, 
                      <%= @button_2_bg_color_saturation %>%, 
                      <%= @button_2_bg_color_luminosity %>%)
                      </li>
                    </ul>
                  </div>"
                >
                Tooltips
              </button>
              <span class="explore-mode not">Off</span>
            </li>
          </div>
        </ul>
      </div>
    </div>
  </div>
</div>
<%= render "partials/instructions_modal" %>

app/views/partials/_instructions_modal.html.erb
<div class="modal fade" id='instructions' tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title">How it Works - Making a Change</h2>
      </div>
      <div class="modal-body">
        <ul>
          <li>Youi uses averaging algorithms to dynamically render styles based on components you like</li>
          <li>Upon clicking a component, you will be brought to a page with our voting panel</li>
          <li>Notice the component you clicked <strong>will have undergone</strong> a change</li>
          <li>Use the voting panel to <strong>like</strong> or <strong>dislike</strong> this change</li>
          <li>You can vote as many times as you want!</li>
          <li>When you want to see your changes, click the 'DONE' button</li>
          <li>Choose wisely!</li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-warning center-block" data-dismiss="modal">Got It</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/partials/_section_link_creator.html.erb
<!-- /** Add Links to entire div without overwriting other click events **/
 -->

<script type="text/javascript">
  function addSectionLinks(section, path){
    $(section).click(function(e) {
       window.location = path; 
    });

    $(`${section} .not`).click(function(e){
      e.stopPropagation();
    });
  }

  function invokeSectionLinks(){
    addSectionLinks(".header", '<%= train_path("section", "section-selector", 1) %>');
    addSectionLinks(".site-editables", '<%= train_path("section", "section-selector", 2, anchor: "fonts") %>');
    addSectionLinks(".info", '<%= train_path("section", "section-selector", 3, anchor: "info") %>');
    addSectionLinks(".footer", '<%= train_path("section", "section-selector", 4, anchor: "foot") %>');
    addSectionLinks('.instruction-buttons', '<%= train_path("button", "button-selector", 2) %>')
    addSectionLinks('.custom-nav', '<%= train_path("li", "li-selector", 1) %>');
  }


  switch("<%= function %>"){
    case "main": invokeSectionLinks(); break;
    case "custom": invokeCustomSectionLinks(); break;
  }
</script>

app/views/partials/_show_stats.html.erb
  <div class='row'>
    <div class='col-md-6'>
      <h2>Fontsize</h2>
      <ul>
        <li>Max: <span class='orange'><%= @fontsize_max %>px</span></li>
        <li>Min: <span class='orange'><%= @fontsize_min %>px</span></li>
        <li>Most Chosen: <span class='orange'><%= @fontsize_most %>px</span></li>
        <li>Least Chosen: <span class='orange'><%= @fontsize_least %>px</span></li>
      </ul>
    </div>
    <div class='col-md-6'>
        <%= column_chart @fontsize, xtitle: "Pixels", ytitle: "Likes", label: "Likes" %>    
    </div>
  </div>
  <hr class='blue-line'>
  <div class='row'>
    <div class='col-md-6'>
      <%= column_chart @letterspacing, xtitle: "Pixels", ytitle: "Likes", label: "Likes" %>
    </div>
    <div class='col-md-6'>
      <h2>Letter Spacing</h2>
      <ul>
        <li>Max: <span class='orange'><%= @letterspacing_max %>px</span></li>
        <li>Min: <span class='orange'><%= @letterspacing_min %>px</span></li>
        <li>Most Chosen: <span class='orange'><%= @letterspacing_most %>px</span></li>
        <li>Least Chosen: <span class='orange'><%= @letterspacing_least %>px</span></li>
      </ul>
    </div>
  </div>
  <hr class='blue-line'>
  <div class='row'>
    <div class='col-md-6'>
      <h2>Font Weight</h2>
      <ul>
        <li>Max: <span class='orange'><%= @fontweight_max %></span></li>
        <li>Min: <span class='orange'><%= @fontweight_min %></span></li>
        <li>Most Chosen: <span class='orange'><%= @fontweight_most %></span></li>
        <li>Least Chosen: <span class='orange'><%= @fontweight_least %></span></li>
      </ul>
    </div>
    <div class='col-md-6'>
       : <span class='orange'><%= column_chart @fontweight, xtitle: "Weight", ytitle: "Likes", label: "Likes" %>    
    </div>
  </div>
  <hr class='blue-line'>
  <div class='row'>
    <div class='col-md-6'>
      <%= column_chart @texttransformation, xtitle: "Transformations", ytitle: "Likes", label: "Likes" %>
    </div>
    <div class='col-md-6'>
      <h2>Text Transformation</h2>
      <ul>
        <li>Most Chosen: <span class='orange'><%= @texttransformation_most %></span></li>
        <li>Least Chosen: <span class='orange'><%= @texttransformation_least %></span></li>
      </ul>
    </div>
  </div>
  <hr class='blue-line'>
  <div class='row'>
    <div class='col-md-6'>
      <h2>Word Spacing</h2>
      <ul>
        <li>Max: <span class='orange'><%= @wordspacing_max %>px</span></li>
        <li>Min: <span class='orange'><%= @wordspacing_min %>px</span></li>
        <li>Most Chosen: <span class='orange'><%= @wordspacing_most %>px</span></li>
        <li>Least Chosen: <span class='orange'><%= @wordspacing_least %>px</span></li>
      </ul>
    </div>
    <div class='col-md-6'>
        <%= column_chart @wordspacing, xtitle: "Pixels", ytitle: "Likes", label: "Likes" %>    
    </div>
  </div>

app/views/partials/_stats_footer.html.erb
<div class='container-fluid stats-footer'>
  <div class='container'>
    <h2>More Choices</h2>
    <hr class='line'>
    <div class='row'>
      
      <%= link_to h1_stats_path do %>
        <div class='col-md-4'>
          <div class='tab'>
            <h3>H1</h3>
          </div>
        </div>
      <% end %>
      
      <%= link_to h2_stats_path do %>
        <div class='col-md-4'>
          <div class='tab'>
            <h3>H2</h3>
          </div>
        </div>
      <% end %>
      
      <%= link_to h3_stats_path do %>
        <div class='col-md-4'>
          <div class='tab'>
            <h3>H3</h3>
          </div>
        </div>
      <% end %>
      
    </div><!-- row -->
    
    <div class='row'>
      
      <%= link_to h4_stats_path do %>
        <div class='col-md-4'>
          <div class='tab'>
            <h3>H4</h3>
          </div>
      </div>
      <% end %>
      
      <%= link_to h5_stats_path do %>
        <div class='col-md-4'>
          <div class='tab'>
            <h3>H5</h3>
          </div>
        </div>
      <% end %>
      
      <%= link_to image_stats_path do %>
        <div class='col-md-4'>
          <div class='tab'>
            <h3>Images</h3>
          </div>
        </div>
      <% end %>
      
    </div><!-- row -->
    
    <div class='row'>
      
      <%= link_to listelement_stats_path do %>
        <div class='col-md-4'>
          <div class='tab'>
            <h3>Navbar</h3>
          </div>
        </div>
      <% end %>
      
      <%= link_to paragraph_stats_path do %>
        <div class='col-md-4'>
          <div class='tab'>
            <h3>Paragraphs</h3>
          </div>
        </div>
      <% end %>
      
      <%= link_to section_stats_path do %>
        <div class='col-md-4'>
          <div class='tab'>
            <h3>Sections</h3>
          </div>
        </div>
      <% end %>
      
    </div><!-- row -->
    
    <div class='row'>
      
      <%= link_to body_stats_path do %>
        <div class='col-md-4'>
          <div class='tab'>
            <h3>Body</h3>
          </div>
        </div>
      <% end %>
      
      <%= link_to button_stats_path do %>
        <div class='col-md-4'>
          <div class='tab'>
            <h3>Buttons</h3>
          </div>
        </div>
      <% end %>
      
      <%= link_to stats_path do %>
        <div class='col-md-4'>
          <div class='tab home-tab'>
            <h3>Site Stats</h3>
          </div>
        </div>
      <% end %>
    </div><!-- row -->
      
    <h5 class='copyright'>Copyright (c) Greg Perlman, 2016</h5>

  </div><!-- container -->
  
  
</div>

app/views/partials/_stats_header.html.erb
<nav class="navbar navbar-default stats-nav">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Youi', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li>
          <%= link_to 'Home', root_path %>
          </li>
          <li>
          <%= link_to 'Custom', user_path(@cookie) %>
          </li>
          <li>
          <%= link_to 'Stats', stats_path, class: "where-am-i" %>
          </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_twitch_info.html.erb
After 16 straight days, over 1.16 million people contributed to beating Pokemon Red. Youi believes that it can use this model to translate global cooperation of a video game to creating a magnificent-looking website. Every change matters!

app/views/partials/_vote_gui.html.erb
<div class='vote-gui' id='dragme'>
  <span class='how-to-use' data-toggle="modal" data-target="#instructions">How to use?</span>
  <hr>
  <h3>Now Editing: <span class='properties'><%= @currently_editing %></span></h3>
  <span class='glyphicon glyphicon-move move'></span>
  <button class='btn btn-success good' data-id="<%= @id %>" data-selector="<%= @class %>" data-model="<%= @model %>">I LIKE THIS</button>
  <button class='btn btn-danger bad' data-selector='<%= @class %>'>I DON'T LIKE THIS</button>
  <hr>
  <div class='current-styles'></div>
  <%= link_to path do %>
    <button class='btn btn-primary'>DONE!</button>
  <% end %>
</div>

<%= render "partials/instructions_modal" %>